### ISSUE TITLE
Error when running a custom track with 1.7.2

### ISSUE THREAD

**Issue by j-bennet** [elastic/rally#582]
**Rally version** (get with `esrally --version`):

```
esrally 1.0.1
```

**Invoked command**:

esrally --distribution-version=1.7.2 --track-path=./rally-tracks/dummy

**Configuration file (located in `~/.rally/rally.ini`))**:

```
[meta]
config.version = 17

[system]
env.name = local

[node]
root.dir = /Users/irina/.rally/benchmarks
src.root.dir = /Users/irina/.rally/benchmarks/src

[source]
remote.repo.url = https://github.com/elastic/elasticsearch.git
elasticsearch.src.subdir = elasticsearch

[benchmarks]
local.dataset.cache = /Users/irina/.rally/benchmarks/data

[reporting]
datastore.type = in-memory
datastore.host =
datastore.port =
datastore.secure =
datastore.user =
datastore.password =

[tracks]
default.url = https://github.com/elastic/rally-tracks

[teams]
default.url = https://github.com/elastic/rally-teams

[defaults]
preserve_benchmark_candidate = False

[distributions]
release.cache = true
```

**JVM version**:

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**OS version**:

```
MacOS High Sierra
10.13.6 (17G2307)
```

**Description of the problem including expected versus actual behavior**:

I created a custom track very much like "example track" (https://esrally.readthedocs.io/en/stable/adding_tracks.html#example-track), but with my own index mappings.

The track works with `--distribution-version=6.4.2` but fails with `1.7.2`:

```
(benchmarks) --- benchmarks/elastic ‹benchmarks/elastic*M?› » esrally --distribution-version=1.7.2 --track-path=./rally-tracks/dummy

    ____        ____
   / __ \____ _/ / /_  __
  / /_/ / __ `/ / / / / /
 / _, _/ /_/ / / / /_/ /
/_/ |_|\__,_/_/_/\__, /
                /____/

[INFO] Preparing for race ...
[INFO] Racing on track [dummy] and car ['defaults'] with version [1.7.2].

Running delete-index                                                           [100% done]
Running create-index                                                           [100% done]
Running cluster-health                                                         [100% done]
Running bulk                                                                   [  0% done]
[ERROR] Cannot race. Error in load generator [0]
	'str' object has no attribute 'get'
```

I attached the log and track files.
[error-1.7-rally.log](https://github.com/elastic/rally/files/2443902/error-1.7-rally.log)
[dummy.zip](https://github.com/elastic/rally/files/2443933/dummy.zip)

**Comment by j-bennet** [comment]
My data had `_id` and `_type` in it, apparently this is a problem. Running with `includes-action-and-meta-data` now, things work. Closing.
